version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-notifications
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb,ses
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  notification-service:
    build: .
    container_name: tickets-notification-service
    ports:
      - "8085:8085"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/main.go

